; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; --- 라이브러리 의존성 추가 ---
lib_deps = 
    NewPing
    witnessmenow/UniversalTelegramBot  ; 텔레그램 봇
    bblanchon/ArduinoJson              ; JSON 처리용

; --- 안정성 확보 (원격 설정 오류 방지) ---
board_build.arduino.upstream_packages = no

; --- 업로드 설정 (최초 1회는 유선 권장) ---
;upload_protocol = esptool

; --- OTA (무선 업로드) 설정 추가 --- 2025.11.12
upload_protocol = espota
upload_port = 192.168.0.91
; --- OTA 파티션 테이블 설정 ---
board_build.partitions = huge_app.csv